
insert into EDWIN_TEAM_CFG
(
  OWNER_TEAM_CODE     
  ,EMAIL_TO_LIST  
  ,SMS_MAIL_TO      
  ,SMS_MAIL_TITLE     
  ,PHONE_MAIL_TO    
  ,PHONE_MAIL_TITLE   
)
VALUES
(
  'EDWIN_OP_TEAM'  --OWNER_TEAM_CODE     
  ,'somebody@corp.com'   --,EMAIL_TO_LIST  
  ,'somebody@corp.com'   --,SMS_MAIL_TO      
  ,'YOUR_SMS_MAIL_TITLE'   --,SMS_MAIL_TITLE     
  ,'somebody@corp.com'   --,PHONE_MAIL_TO    
  ,'YOUR_PHONE_MAIL_TITLE'   --,PHONE_MAIL_TITLE
)
;


insert into EDWIN_TEAM_CFG
(
  OWNER_TEAM_CODE     
  ,EMAIL_TO_LIST  
  ,SMS_MAIL_TO      
  ,SMS_MAIL_TITLE     
  ,PHONE_MAIL_TO    
  ,PHONE_MAIL_TITLE   
)
VALUES
(
  'EDWIN_DEV_TEAM'  --OWNER_TEAM_CODE     
  ,'somebody@corp.com'   --,EMAIL_TO_LIST  
  ,'somebody@corp.com'   --,SMS_MAIL_TO      
  ,'YOUR_SMS_MAIL_TITLE'   --,SMS_MAIL_TITLE     
  ,'somebody@corp.com'   --,PHONE_MAIL_TO    
  ,'PHONE_MAIL_TITLE'   --,PHONE_MAIL_TITLE
)
;


 